- name: enable geonode ppa
  apt_repository: repo='ppa:geonode/testing' update_cache=yes
- name: install prerequisite packages
  apt: pkg={{ item }} state=latest
  with_items:
    - geonode
- name: set IP addresses for geonode
  command: geonode-updateip {{ geonode_ip }}
  sudo: yes
- name: create geonode django superuser
  command: geonode createsuperuser
  sudo: yes
