---
- name: install useful packages
  apt: pkg={{ item }} update_cache=yes state=present
  with_items:
    - build-essential
    - byobu
    - dnsutils
    - git
    - htop
    - lsof
    - sshguard
    - fail2ban
    - iftop
    - iotop
    - iptraf
    - libpam-abl
    - libwww-perl
    - mailutils
    - mercurial
    - mpack
    - netcat-traditional
    - nmap
    - postfix
    - pwgen
    - python-passlib
    - python-pycurl
    - screen
    - ssl-cert
    - subversion
    - sudo
    - sysstat
    - tcptraceroute
    - telnet
    - tmux
    - traceroute
    - unzip
    - uuid
    - vim-nox
    - zsh
  #gdal-bin python-psycopg2 mutt gpsbabel
