# File to setup backup related stuff
---

#Not yet thought out as several things require manual thinking for now :(

- hosts: all
  tags: backupScripts
  sudo: yes
  tasks:
    - name: confirm duplicity installed
      apt: pkg=duplicity update_cache=no state=present
    - name: /usrlocal/bin
      file: path=/usr/local/bin mode=0755 owner=root state=directory
    - name: Backup dirs
      file: path={{item}} mode=0777 owner=root state=directory
      with_items:
        - /data/backups
        - /data/dbbackups
    - name: insert scripts for backup File
      copy: src=files/{{ item }} dest=/usr/local/bin mode=0555 owner=root
      with_items:
        - duplicityDailyBackup
        - duplicityWeeklyBackup
    - name: insert cron
      copy: src=files/duplicityCron dest=/etc/cron.d/ mode=0444 owner=root

