---
- name: create drbd0 device if not found
  hosts: proxmox
  tasks:
    - name: check for drbd0 device
      shell: ls /dev/drbd0
      register: drbd_device
      changed_when: False
    - name: stop the drbd service
      service: name=drbd state=stopped
      when: drbd_device.rc > 0
    - name: zero out any filesystem metadata
      command: dd if=/dev/zero of=/dev/md2 bs=8M count=32
      when: drbd_device.rc > 0
    - name: load the drbd kernel module
      modprobe: name=drbd state=present
      when: drbd_device.rc > 0
    - name: create virt0 device
      command: drbdadm create-md virt0
      when: drbd_device.rc > 0
    - name: start the drbd service
      service: name=drbd state=started
      when: drbd_device.rc > 0

- name: elect an initial primary node
  hosts: proxmox1.inasafe.com
  tasks:
    - name: set as primary
      command: drbdsetup /dev/drbd0 primary -o
      when: drbd_device.rc > 0

- name: connect the secondary node
  hosts: proxmox2.inasafe.com
  tasks:
    - name: connect to primary
      command: drbdadm connect virt0
      when: drbd_device.rc > 0

- name: check for completed drbd setup and create shared volume group
  hosts: proxmox
  tasks:
    - name: check for completed drbd setup
      shell: cat /proc/drbd | grep '^ 0:' | grep cs:Connected | grep Primary/Primary | grep UpToDate/UpToDate
      register: drbd_status
      changed_when: False
    - name: abort if primary/primary synchronised drbd not detected
      fail: msg="DRBD setup not completed. Please run `ansible-playbook -i production.ini drbd.yml` and ensure the drbd device has completed syncing before continuing"
      when: drbd_status.rc > 0
    - name: configure shared volume group
      lvg: vg=vg_shared pvs=/dev/drbd0 state=present
